name: "gcloud infrastructure scripts"
description: "gcloud shell scripts for creating infrastructure scripts"
inputs:
  project-id:
    description: "Project ID"
    required: true
  topic-name:
    description: "Topic name"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        # Create pubsub topic for the project
        OUT=$(gcloud pubsub topics create --project=${{ inputs.project-id }} --message-retention-duration=31d ${{ inputs.topic-name }} 2>&1 >/dev/null)

        echo $OUT
      shell: bash
