name: "gcloud infrastructure scripts"
description: "gcloud shell scripts for creating infrastructure scripts"
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: echo "FIRST >>> ${{ inputs.who-to-greet}} SECOND >>> $INPUT_WHO_TO_GREET THIRD >>> $INPUTS_WHO_TO_GREET"
      shell: bash
    - run: ls -al
      shell: bash
    - run: cat pubsub.sh
      shell: bash
